apiVersion: apps/v1
kind: Deployment
metadata:
  name: caam-sbs-api-celery-beat
  labels:
    deployment: caam-sbs-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: caam-sbs-api-celery-beat
  template:
    metadata:
      labels:
        pod: caam-sbs-api-celery-beat
    spec:
      containers:
        - name: caam-sbs-api-celery-beat
          image: syafiqpipe/caam-sbs-api
          # celery -A caam-sbsapi beat -l debug
          command: ['celery', '-A', 'core', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: caam-sbs-api-secret   