# Generated by Django 2.2.6 on 2020-10-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20201005_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callsign',
            options={},
        ),
        migrations.AlterField(
            model_name='callsign',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
