# Generated by Django 2.2.6 on 2020-10-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20201018_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsign',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid'),
        ),
    ]
