# Generated by Django 2.2.6 on 2020-11-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20201018_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpldatahistory',
            name='reason',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='fpldatahistory',
            name='remark',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
