# Generated by Django 2.2.6 on 2020-11-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20201111_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpldata',
            name='reason',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='remark',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
