export const UserPrivileges: any = [
  { id: 1, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 2, module: "reporting", usertype: "headquarter", yesno: true },
  { id: 3, module: "analysis", usertype: "checker marker", yesno: true },
  { id: 4, module: "utility", usertype: "customer", yesno: true },
  { id: 5, module: "management", usertype: "checker marker", yesno: false },
  { id: 6, module: "analysis", usertype: "headquarter", yesno: true },
  { id: 7, module: "management", usertype: "checker marker", yesno: true },
  { id: 8, module: "finance", usertype: "checker marker", yesno: true },
  { id: 9, module: "vfr", usertype: "customer", yesno: true },
  { id: 10, module: "invoice", usertype: "checker marker", yesno: false },
  { id: 11, module: "vfr", usertype: "checker marker", yesno: true },
  { id: 12, module: "management", usertype: "checker marker", yesno: true },
  { id: 13, module: "finance", usertype: "customer", yesno: false },
  { id: 14, module: "analysis", usertype: "headquarter", yesno: true },
  { id: 15, module: "reporting", usertype: "headquarter", yesno: false },
  { id: 16, module: "database", usertype: "checker marker", yesno: false },
  { id: 17, module: "reporting", usertype: "headquarter", yesno: false },
  { id: 18, module: "management", usertype: "customer", yesno: true },
  { id: 19, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 20, module: "reporting", usertype: "checker marker", yesno: true },
  { id: 21, module: "invoice", usertype: "checker marker", yesno: false },
  { id: 22, module: "vfr", usertype: "headquarter", yesno: true },
  { id: 23, module: "reporting", usertype: "customer", yesno: true },
  { id: 24, module: "reporting", usertype: "headquarter", yesno: true },
  { id: 25, module: "utility", usertype: "customer", yesno: false },
  { id: 26, module: "analysis", usertype: "checker marker", yesno: true },
  { id: 27, module: "invoice", usertype: "customer", yesno: false },
  { id: 28, module: "invoice", usertype: "customer", yesno: true },
  { id: 29, module: "utility", usertype: "checker marker", yesno: true },
  { id: 30, module: "management", usertype: "headquarter", yesno: false },
  { id: 31, module: "analysis", usertype: "headquarter", yesno: true },
  { id: 32, module: "vfr", usertype: "headquarter", yesno: false },
  { id: 33, module: "invoice", usertype: "headquarter", yesno: true },
  { id: 34, module: "database", usertype: "checker marker", yesno: false },
  { id: 35, module: "reporting", usertype: "headquarter", yesno: false },
  { id: 36, module: "vfr", usertype: "customer", yesno: true },
  { id: 37, module: "vfr", usertype: "headquarter", yesno: true },
  { id: 38, module: "database", usertype: "customer", yesno: false },
  { id: 39, module: "database", usertype: "customer", yesno: true },
  { id: 40, module: "utility", usertype: "customer", yesno: false },
  { id: 41, module: "management", usertype: "headquarter", yesno: true },
  { id: 42, module: "reporting", usertype: "customer", yesno: true },
  { id: 43, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 44, module: "reporting", usertype: "customer", yesno: false },
  { id: 45, module: "management", usertype: "checker marker", yesno: true },
  { id: 46, module: "vfr", usertype: "customer", yesno: true },
  { id: 47, module: "vfr", usertype: "headquarter", yesno: true },
  { id: 48, module: "utility", usertype: "headquarter", yesno: false },
  { id: 49, module: "utility", usertype: "customer", yesno: true },
  { id: 50, module: "reporting", usertype: "customer", yesno: false },
  { id: 51, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 52, module: "management", usertype: "customer", yesno: true },
  { id: 53, module: "utility", usertype: "headquarter", yesno: true },
  { id: 54, module: "analysis", usertype: "headquarter", yesno: false },
  { id: 55, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 56, module: "analysis", usertype: "checker marker", yesno: true },
  { id: 57, module: "database", usertype: "headquarter", yesno: false },
  { id: 58, module: "vfr", usertype: "headquarter", yesno: false },
  { id: 59, module: "invoice", usertype: "checker marker", yesno: false },
  { id: 60, module: "database", usertype: "customer", yesno: true },
  { id: 61, module: "analysis", usertype: "checker marker", yesno: false },
  { id: 62, module: "utility", usertype: "headquarter", yesno: true },
  { id: 63, module: "database", usertype: "customer", yesno: true },
  { id: 64, module: "database", usertype: "checker marker", yesno: true },
  { id: 65, module: "vfr", usertype: "customer", yesno: false },
  { id: 66, module: "finance", usertype: "headquarter", yesno: true },
  { id: 67, module: "invoice", usertype: "checker marker", yesno: true },
  { id: 68, module: "database", usertype: "headquarter", yesno: false },
  { id: 69, module: "management", usertype: "customer", yesno: true },
  { id: 70, module: "analysis", usertype: "checker marker", yesno: true },
  { id: 71, module: "analysis", usertype: "customer", yesno: true },
  { id: 72, module: "finance", usertype: "headquarter", yesno: false },
  { id: 73, module: "invoice", usertype: "customer", yesno: false },
  { id: 74, module: "utility", usertype: "checker marker", yesno: true },
  { id: 75, module: "finance", usertype: "checker marker", yesno: false },
  { id: 76, module: "utility", usertype: "checker marker", yesno: false },
  { id: 77, module: "reporting", usertype: "checker marker", yesno: true },
  { id: 78, module: "reporting", usertype: "checker marker", yesno: false },
  { id: 79, module: "analysis", usertype: "checker marker", yesno: true },
  { id: 80, module: "finance", usertype: "checker marker", yesno: true },
  { id: 81, module: "reporting", usertype: "headquarter", yesno: false },
  { id: 82, module: "utility", usertype: "checker marker", yesno: false },
  { id: 83, module: "management", usertype: "headquarter", yesno: true },
  { id: 84, module: "reporting", usertype: "checker marker", yesno: true },
  { id: 85, module: "utility", usertype: "checker marker", yesno: true },
  { id: 86, module: "database", usertype: "headquarter", yesno: false },
  { id: 87, module: "database", usertype: "checker marker", yesno: false },
  { id: 88, module: "management", usertype: "headquarter", yesno: false },
  { id: 89, module: "management", usertype: "customer", yesno: true },
  { id: 90, module: "management", usertype: "headquarter", yesno: false },
  { id: 91, module: "utility", usertype: "customer", yesno: true },
  { id: 92, module: "utility", usertype: "customer", yesno: false },
  { id: 93, module: "management", usertype: "customer", yesno: true },
  { id: 94, module: "vfr", usertype: "headquarter", yesno: false },
  { id: 95, module: "management", usertype: "headquarter", yesno: true },
  { id: 96, module: "utility", usertype: "headquarter", yesno: false },
  { id: 97, module: "analysis", usertype: "headquarter", yesno: true },
  { id: 98, module: "invoice", usertype: "checker marker", yesno: true },
  { id: 99, module: "utility", usertype: "checker marker", yesno: true },
  { id: 100, module: "analysis", usertype: "checker marker", yesno: false }
];
