# Generated by Django 2.2.6 on 2020-10-05 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_involve', models.CharField(default='NA', max_length=100)),
                ('action_done', models.CharField(choices=[('CRT', 'Create'), ('EDT', 'Edit'), ('DLT', 'Delete'), ('DWL', 'Download'), ('UPL', 'Upload'), ('EXP', 'Export'), ('PRT', 'Print'), ('NA', 'Not Available')], default='NAN', max_length=3)),
                ('origin_info', models.CharField(default='NA', max_length=100)),
                ('updated_info', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
