# Generated by Django 2.2.6 on 2020-10-05 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audittrails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
