# Generated by Django 2.2.6 on 2020-10-05 04:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('registration_num', models.CharField(default='NA', max_length=100)),
                ('model', models.CharField(default='NA', max_length=100)),
                ('aircraft_type', models.CharField(choices=[('H', 'Chopper'), ('FW', 'Fixed Wing'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('weight_category', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'organisation_type': 'MN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_airline', to='organisations.Organisation')),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'organisation_type': 'AL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_operator', to='organisations.Organisation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
