# Generated by Django 2.2.6 on 2020-10-05 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aid', models.CharField(default='NA', max_length=4)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('icao_code', models.CharField(default='NA', max_length=100)),
                ('iata_code', models.CharField(default='NA', max_length=100)),
                ('country', models.CharField(default='NA', max_length=100)),
                ('country_code', models.CharField(default='NA', max_length=100)),
                ('airport_category', models.CharField(choices=[('D', 'Domestic'), ('I', 'International'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('office_num', models.CharField(default='NA', max_length=100)),
                ('mobile_num', models.CharField(default='NA', max_length=100)),
                ('fax_num', models.CharField(default='NA', max_length=100)),
                ('pic_name', models.CharField(default='NA', max_length=100)),
                ('pic_num', models.CharField(default='NA', max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
