export const FromAirports: any = [
  {
    no: "1",
    callsign: "MARITIME700",
    registration: "",
    groundhandler: "",
    altmod: "CL415",
    model: "CL415",
    toa: "FW",
    dep: "0KM1",
    arrovf: "AMNC",
    operator: "APMM",
    from: "",
    ata: "1150",
    to: "WBGG",
    atd: "1001",
    fr: "I",
    tof: "D",
    cl: "",
    total: "1",
    remarks: "",
    error: "Grasshopper",
    maximum: 4400,
    distance: 3597,
    dateofflight: 20200206,
    status: "Error"
  },
  {
    no: "2",
    callsign: "GADING TAJAM",
    registration: "",
    groundhandler: "",
    altmod: "EC725",
    model: "EC725",
    toa: "H",
    dep: "0LT3",
    arrovf: "ANA1",
    operator: "TUDM",
    from: "LOCAL",
    ata: "1150",
    to: "LOCAL",
    atd: "2353",
    fr: "V",
    tof: "D",
    cl: "",
    total: "2",
    remarks: "FLYPAST",
    error: "Double Flight Information",
    maximum: 4300,
    distance: 3336,
    dateofflight: 20200206,
    status: "Error"
  },
  {
    no: "3",
    callsign: "GADING TAJAM",
    registration: "",
    groundhandler: "",
    altmod: "EC725",
    model: "EC725",
    toa: "H",
    dep: "0MDW",
    arrovf: "ANC1",
    operator: "TUDM",
    from: "LOCAL",
    ata: "1150",
    to: "LOCAL",
    atd: "2353",
    fr: "V",
    tof: "D",
    cl: "",
    total: "2",
    remarks: "FLYPAST",
    error: "",
    maximum: 5080,
    distance: 3427,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "4",
    callsign: "GADING TAJAM",
    registration: "",
    groundhandler: "",
    altmod: "EC725",
    model: "EC725",
    toa: "H",
    dep: "0NG1",
    arrovf: "ANE1",
    operator: "TUDM",
    from: "LOCAL",
    ata: "1150",
    to: "LOCAL",
    atd: "2353",
    fr: "V",
    tof: "D",
    cl: "",
    total: "2",
    remarks: "FLYPAST",
    error: "Wrong Operator Name",
    maximum: 69000,
    distance: 2674,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "5",
    callsign: "ADVV01",
    registration: "",
    groundhandler: "",
    altmod: "C172",
    model: "C172",
    toa: "FW",
    dep: "0NG3",
    arrovf: "APHO",
    operator: "Air Adventure Flying Club",
    from: "LOCAL",
    ata: "1300",
    to: "LOCAL",
    atd: "3750",
    fr: "V",
    tof: "D",
    cl: "",
    total: "2",
    remarks: "KAPAR",
    error: "",
    maximum: 15876,
    distance: 1502,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "6",
    callsign: "9MIMW",
    registration: "",
    groundhandler: "",
    altmod: "",
    model: "B407",
    toa: "H",
    dep: "0NG5",
    arrovf: "APTO",
    operator: "Systematic Aviation",
    from: "",
    ata: "1320",
    to: "WMKJ",
    atd: "1311",
    fr: "V",
    tof: "D",
    cl: "",
    total: "1",
    remarks: "",
    error: "Wrong Aircraft Route Taken",
    maximum: 170859,
    distance: 3086,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "7",
    callsign: "MARITIME700",
    registration: "",
    groundhandler: "",
    altmod: "CL415",
    model: "CL415",
    toa: "FW",
    dep: "0NG8",
    arrovf: "ARAU",
    operator: "APMM",
    from: "WMSA",
    ata: "1530",
    to: "",
    atd: "1980",
    fr: "I",
    tof: "D",
    cl: "",
    total: "1",
    remarks: "WMSA-WBGG RTB",
    error: "",
    maximum: 150314,
    distance: 2246,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "8",
    callsign: "T7LKT",
    registration: "",
    groundhandler: "",
    altmod: "",
    model: "GLF6",
    toa: "FW",
    dep: "0SJ3",
    arrovf: "ARGH",
    operator: "TAG SAN MARINO",
    from: "WSSL",
    ata: "1560",
    to: "",
    atd: "1870",
    fr: "I",
    tof: "I",
    cl: "",
    total: "1",
    remarks: "",
    error: "Repetitive Callsign",
    maximum: 4400,
    distance: 2607,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "9",
    callsign: "N9688R",
    registration: "",
    groundhandler: "",
    altmod: "",
    model: "E55P",
    toa: "FW",
    dep: "0SP3",
    arrovf: "ARKH",
    operator: "Leicester Asset Holding Ltd",
    from: "",
    ata: "1560",
    to: "WSSL",
    atd: "2060",
    fr: "I",
    tof: "I",
    cl: "",
    total: "1",
    remarks: "",
    error: "Flight Time Inaccurate",
    maximum: 4300,
    distance: 2221,
    dateofflight: 20200206,
    status: "Complete"
  },
  {
    no: "10",
    callsign: "9MHCB",
    registration: "",
    groundhandler: "",
    altmod: "",
    model: "G2CA",
    toa: "FW",
    dep: "0SSI",
    arrovf: "ARPH",
    operator: "Systematic Aviation Services",
    from: "",
    ata: "1980",
    to: "SERENDAH",
    atd: "2090",
    fr: "V",
    tof: "D",
    cl: "",
    total: "1",
    remarks: "",
    error: "",
    maximum: 5080,
    distance: 2667,
    dateofflight: 20200206,
    status: "Complete"
  }
];
