export const RoutelistKuc: any = [
  {
    ln: "1",
    rtid: "1780",
    dep: "PSBU",
    dest: "WBGK",
    dist: "38",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "2",
    rtid: "1782",
    dep: "PSBU",
    dest: "WBGP",
    dist: "84",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "3",
    rtid: "1783",
    dep: "PSBU",
    dest: "WBGY",
    dist: "71",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "4",
    rtid: "1784",
    dep: "PSBU",
    dest: "WBGR",
    dist: "176",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "5",
    rtid: "1785",
    dep: "WBGB",
    dest: "WBGG",
    dist: "194",
    routedesc: "G460",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "6",
    rtid: "1785",
    dep: "WBGG",
    dest: "LOCL",
    dist: "176",
    routedesc: "DCT 176 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "7",
    rtid: "1786",
    dep: "WBGG",
    dest: "LOCL",
    dist: "246",
    routedesc: "DCT 246 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "8",
    rtid: "1790",
    dep: "WBGC",
    dest: "WBGJ",
    dist: "67",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "9",
    rtid: "1791",
    dep: "WBGC",
    dest: "WBGR",
    dist: "281",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "10",
    rtid: "1792",
    dep: "WBGC",
    dest: "WBGZ",
    dist: "93",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "11",
    rtid: "1793",
    dep: "WBGC",
    dest: "WBKK",
    dist: "157",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "12",
    rtid: "1794",
    dep: "WBGG",
    dest: "WBKL",
    dist: "376",
    routedesc: "G580 B348",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "13",
    rtid: "1797",
    dep: "WBGG",
    dest: "PSBU",
    dist: "112",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "14",
    rtid: "1798",
    dep: "WBGG",
    dest: "RJAA",
    dist: "567",
    routedesc: "G580 B348",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "15",
    rtid: "1799",
    dep: "WBGG",
    dest: "RKSI",
    dist: "567",
    routedesc: "G580 B348",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "16",
    rtid: "1800",
    dep: "WBGG",
    dest: "RPLL",
    dist: "567",
    routedesc: "G580 B348",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "17",
    rtid: "1801",
    dep: "WBGG",
    dest: "VHHH",
    dist: "545",
    routedesc: "G580 M754",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "18",
    rtid: "1803",
    dep: "WBGG",
    dest: "WBGC",
    dist: "239",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "19",
    rtid: "1804",
    dep: "WBGG",
    dest: "WBGK",
    dist: "136",
    routedesc: "G580 PILAX DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "20",
    rtid: "1805",
    dep: "WBGG",
    dest: "WBGP",
    dist: "158",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "21",
    rtid: "1806",
    dep: "WBGG",
    dest: "WBGR",
    dist: "281",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "22",
    rtid: "1807",
    dep: "WBGG",
    dest: "WBGS",
    dist: "112",
    routedesc: "G460",
    cs: "333",
    cat: "D"
  },
  {
    ln: "23",
    rtid: "1808",
    dep: "WBGG",
    dest: "WBGT",
    dist: "75",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "24",
    rtid: "1809",
    dep: "WBGG",
    dest: "WBGY",
    dist: "70",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "25",
    rtid: "1810",
    dep: "WBGG",
    dest: "WBKD",
    dist: "586",
    routedesc: "G580",
    cs: "222",
    cat: "D"
  },
  {
    ln: "26",
    rtid: "1811",
    dep: "WBGG",
    dest: "WBKK",
    dist: "434",
    routedesc: "G580 M646",
    cs: "333",
    cat: "D"
  },
  {
    ln: "27",
    rtid: "1812",
    dep: "WBGG",
    dest: "WBKL",
    dist: "376",
    routedesc: "G580 BRU DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "28",
    rtid: "1813",
    dep: "WBGG",
    dest: "WBKW",
    dist: "543",
    routedesc: "G580 W453",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "29",
    rtid: "1818",
    dep: "WBGG",
    dest: "WIOO",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "D"
  },
  {
    ln: "30",
    rtid: "1819",
    dep: "WBGG",
    dest: "WMKC",
    dist: "113",
    routedesc: "M761",
    cs: "333",
    cat: "D"
  },
  {
    ln: "31",
    rtid: "1820",
    dep: "WBGG",
    dest: "WMKI",
    dist: "113",
    routedesc: "M761",
    cs: "333",
    cat: "D"
  },
  {
    ln: "32",
    rtid: "1821",
    dep: "WBGG",
    dest: "WMKK",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "33",
    rtid: "1822",
    dep: "WBGG",
    dest: "WMKL",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "34",
    rtid: "1823",
    dep: "WBGG",
    dest: "WMKN",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "35",
    rtid: "1824",
    dep: "WBGG",
    dest: "WMKP",
    dist: "113",
    routedesc: "M761",
    cs: "333",
    cat: "D"
  },
  {
    ln: "36",
    rtid: "1826",
    dep: "WBGG",
    dest: "YPPH",
    dist: "19",
    routedesc: "R455",
    cs: "333",
    cat: "D"
  },
  {
    ln: "37",
    rtid: "1827",
    dep: "WBGG",
    dest: "ZSFZ",
    dist: "545",
    routedesc: "G580 M754",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "38",
    rtid: "1828",
    dep: "WBGI",
    dest: "WBGM",
    dist: "47",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 2 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "39",
    rtid: "1830",
    dep: "WBGJ",
    dest: "WBGG",
    dist: "353",
    routedesc: "W450 G580",
    cs: "333",
    cat: "D"
  },
  {
    ln: "40",
    rtid: "1833",
    dep: "WBGJ",
    dest: "WBGW",
    dist: "23",
    routedesc: "DCT",
    cs: "333",
    cat: "D"
  },
  {
    ln: "41",
    rtid: "1836",
    dep: "WBGK",
    dest: "WBGR",
    dist: "142",
    routedesc: "DCT SARVO",
    cs: "222",
    cat: "D"
  },
  {
    ln: "42",
    rtid: "1837",
    dep: "WBGL",
    dest: "WBGM",
    dist: "61",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "43",
    rtid: "1839",
    dep: "WBGM",
    dest: "WBGG",
    dist: "292",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "44",
    rtid: "1841",
    dep: "WBGM",
    dest: "WBGR",
    dist: "21",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "45",
    rtid: "1846",
    dep: "WBGP",
    dest: "WBGC",
    dist: "64",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "46",
    rtid: "1848",
    dep: "WBGR",
    dest: "WBGB",
    dist: "90",
    routedesc: "G460",
    cs: "222",
    cat: "D"
  },
  {
    ln: "47",
    rtid: "1863",
    dep: "WBGW",
    dest: "WBGD",
    dist: "38",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "48",
    rtid: "1864",
    dep: "WBGW",
    dest: "WBGG",
    dist: "353",
    routedesc: "G580",
    cs: "222",
    cat: "D"
  },
  {
    ln: "49",
    rtid: "1865",
    dep: "WBGW",
    dest: "WBGQ",
    dist: "54",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "50",
    rtid: "1868",
    dep: "WBGZ",
    dest: "WBGQ",
    dist: "27",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "51",
    rtid: "1876",
    dep: "WBKK",
    dest: "WBKL",
    dist: "62",
    routedesc: "DCT",
    cs: "222",
    cat: "D"
  },
  {
    ln: "52",
    rtid: "1894",
    dep: "WBKS",
    dest: "WBGG",
    dist: "558",
    routedesc: "A341 G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "53",
    rtid: "1912",
    dep: "WBGG",
    dest: "WSSS",
    dist: "109",
    routedesc: "G580",
    cs: "222",
    cat: "I"
  },
  {
    ln: "54",
    rtid: "1914",
    dep: "WBGG",
    dest: "WMKJ",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "55",
    rtid: "1931",
    dep: "WIII",
    dest: "WBGG",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "56",
    rtid: "1932",
    dep: "VMMC",
    dest: "WBGG",
    dist: "545",
    routedesc: "M754 G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "57",
    rtid: "1944",
    dep: "WBGG",
    dest: "WBGG",
    dist: "0",
    routedesc: "RETURN TO BASE",
    cs: "222",
    cat: "D"
  },
  {
    ln: "58",
    rtid: "1945",
    dep: "WSSL",
    dest: "WBGG",
    dist: "109",
    routedesc: "B348",
    cs: "222",
    cat: "I"
  },
  {
    ln: "59",
    rtid: "1946",
    dep: "WBGG",
    dest: "WADD",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "60",
    rtid: "1951",
    dep: "WBGG",
    dest: "WMKD",
    dist: "113",
    routedesc: "M761",
    cs: "222",
    cat: "D"
  },
  {
    ln: "61",
    rtid: "1952",
    dep: "WBGG",
    dest: "WIHH",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "62",
    rtid: "1954",
    dep: "WIIH",
    dest: "WBGG",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "63",
    rtid: "1955",
    dep: "WPDL",
    dest: "WBGG",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "64",
    rtid: "1956",
    dep: "WBGG",
    dest: "WMKA",
    dist: "113",
    routedesc: "M761",
    cs: "222",
    cat: "D"
  },
  {
    ln: "65",
    rtid: "1958",
    dep: "WBGG",
    dest: "VIDP",
    dist: "113",
    routedesc: "M761",
    cs: "222",
    cat: "I"
  },
  {
    ln: "66",
    rtid: "1963",
    dep: "WBGG",
    dest: "WRRR",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "67",
    rtid: "1969",
    dep: "WBGG",
    dest: "ZSHC",
    dist: "545",
    routedesc: "G580 M754",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "68",
    rtid: "1979",
    dep: "WBGG",
    dest: "VVNB",
    dist: "113",
    routedesc: "M761",
    cs: "222",
    cat: "I"
  },
  {
    ln: "69",
    rtid: "1980",
    dep: "WBGG",
    dest: "WIPP",
    dist: "19",
    routedesc: "R455",
    cs: "222",
    cat: "I"
  },
  {
    ln: "70",
    rtid: "1981",
    dep: "WBGG",
    dest: "WSAP",
    dist: "109",
    routedesc: "G580",
    cs: "222",
    cat: "I"
  },
  {
    ln: "71",
    rtid: "1990",
    dep: "WBSB",
    dest: "WBGG",
    dist: "342",
    routedesc: "G580",
    cs: "SC3",
    cat: "I"
  },
  {
    ln: "72",
    rtid: "1991",
    dep: "WBGG",
    dest: "WBSB",
    dist: "342",
    routedesc: "G580",
    cs: "SC3",
    cat: "I"
  },
  {
    ln: "73",
    rtid: "2001",
    dep: "WIOO",
    dest: "WBGG",
    dist: "19",
    routedesc: "R455",
    cs: "SC3",
    cat: "I"
  },
  {
    ln: "74",
    rtid: "2007",
    dep: "WSAP",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "222",
    cat: "I"
  },
  {
    ln: "75",
    rtid: "2008",
    dep: "WSSS",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580 VKG DCT",
    cs: "SC3",
    cat: "I"
  },
  {
    ln: "76",
    rtid: "2009",
    dep: "WBTM",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT PILAX G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 3 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "77",
    rtid: "2010",
    dep: "WBGG",
    dest: "WBTM",
    dist: "75",
    routedesc: "G580 PILAX DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "78",
    rtid: "2011",
    dep: "WMKJ",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "79",
    rtid: "2012",
    dep: "WMKL",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "80",
    rtid: "2013",
    dep: "WSAP",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "81",
    rtid: "2014",
    dep: "WBGG",
    dest: "WSSL",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "82",
    rtid: "2015",
    dep: "WSSL",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "83",
    rtid: "2016",
    dep: "WBGG",
    dest: "WBMU",
    dist: "315",
    routedesc: "G460 VBU W448",
    cs: "222",
    cat: "D"
  },
  {
    ln: "84",
    rtid: "2016",
    dep: "WBGG",
    dest: "WMKM",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "85",
    rtid: "2017",
    dep: "WMKM",
    dest: "WBGG",
    dist: "109",
    routedesc: "G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "86",
    rtid: "2018",
    dep: "WBGK",
    dest: "WBGG",
    dist: "136",
    routedesc: "DCT PILAX G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "87",
    rtid: "2019",
    dep: "WBGG",
    dest: "WIII",
    dist: "19",
    routedesc: "R455",
    cs: "SC3",
    cat: "I"
  },
  {
    ln: "88",
    rtid: "2019",
    dep: "WBGG",
    dest: "VMMC",
    dist: "545",
    routedesc: "G580 M754",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "89",
    rtid: "2020",
    dep: "WADD",
    dest: "WBGG",
    dist: "19",
    routedesc: "R455",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "90",
    rtid: "2021",
    dep: "WMKK",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "91",
    rtid: "2022",
    dep: "WMSA",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "92",
    rtid: "2023",
    dep: "WBGG",
    dest: "WMSA",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "93",
    rtid: "2024",
    dep: "WMKP",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "94",
    rtid: "2025",
    dep: "VIDP",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "95",
    rtid: "2026",
    dep: "VVNB",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "96",
    rtid: "2027",
    dep: "WBGG",
    dest: "WMKB",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "97",
    rtid: "2028",
    dep: "WMKA",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "98",
    rtid: "2029",
    dep: "WMKF",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "99",
    rtid: "2030",
    dep: "WBGK",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "100",
    rtid: "2031",
    dep: "WBGG",
    dest: "WBGK",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "101",
    rtid: "2032",
    dep: "WBGG",
    dest: "WMKF",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "102",
    rtid: "2033",
    dep: "WMKI",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "103",
    rtid: "2034",
    dep: "WMKC",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "104",
    rtid: "2035",
    dep: "WMKN",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "105",
    rtid: "2036",
    dep: "WMKD",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "106",
    rtid: "2037",
    dep: "WBMU",
    dest: "WBGG",
    dist: "315",
    routedesc: "W448 VBU G460",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "107",
    rtid: "2038",
    dep: "WBKW",
    dest: "WBGG",
    dist: "543",
    routedesc: "W453 G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "108",
    rtid: "2039",
    dep: "WBKK",
    dest: "WBGG",
    dist: "434",
    routedesc: "G580 M646",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "109",
    rtid: "2040",
    dep: "WBKL",
    dest: "WBGG",
    dist: "376",
    routedesc: "DCT BRU G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "110",
    rtid: "2041",
    dep: "WBGG",
    dest: "WBGJ",
    dist: "353",
    routedesc: "G580 W450",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "111",
    rtid: "2042",
    dep: "WBGG",
    dest: "WBKS",
    dist: "558",
    routedesc: "G580 A341",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "112",
    rtid: "2043",
    dep: "WBGS",
    dest: "WBGG",
    dist: "112",
    routedesc: "G460",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "113",
    rtid: "2044",
    dep: "WBGG",
    dest: "WBGB",
    dist: "194",
    routedesc: "G460",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "114",
    rtid: "2045",
    dep: "KPBD",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 4 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "115",
    rtid: "2046",
    dep: "WBGG",
    dest: "KPBD",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "116",
    rtid: "2047",
    dep: "KPSE",
    dest: "WBGG",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "117",
    rtid: "2048",
    dep: "WBGG",
    dest: "KPSE",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "118",
    rtid: "2049",
    dep: "SAPT",
    dest: "WBGG",
    dist: "20",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "119",
    rtid: "2050",
    dep: "WBGG",
    dest: "SAPT",
    dist: "20",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "120",
    rtid: "2051",
    dep: "PLBR",
    dest: "WBGG",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "121",
    rtid: "2052",
    dep: "WBGG",
    dest: "PLBR",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "122",
    rtid: "2053",
    dep: "ENTB",
    dest: "WBGG",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "123",
    rtid: "2054",
    dep: "WBGG",
    dest: "ASUM",
    dist: "20",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "124",
    rtid: "2055",
    dep: "TEKJ",
    dest: "WBGG",
    dist: "120",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "125",
    rtid: "2056",
    dep: "WBGG",
    dest: "TEKJ",
    dist: "120",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "126",
    rtid: "2057",
    dep: "MRAS",
    dest: "WBGG",
    dist: "17",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "127",
    rtid: "2058",
    dep: "RJOY",
    dest: "WBGG",
    dist: "17",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "128",
    rtid: "2059",
    dep: "WBGG",
    dest: "RJOY",
    dist: "17",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "129",
    rtid: "2060",
    dep: "GRNG",
    dest: "WBGG",
    dist: "158",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "130",
    rtid: "2061",
    dep: "WBGG",
    dest: "GRNG",
    dist: "158",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "131",
    rtid: "2062",
    dep: "WBGG",
    dest: "WBKL",
    dist: "376",
    routedesc: "G580 B348",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "132",
    rtid: "2063",
    dep: "WBGG",
    dest: "DBAK",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "133",
    rtid: "2064",
    dep: "ULLR",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "134",
    rtid: "2065",
    dep: "WBGG",
    dest: "DARO",
    dist: "84",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "135",
    rtid: "2066",
    dep: "MATU",
    dest: "WBGG",
    dist: "84",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "136",
    rtid: "2067",
    dep: "WBGG",
    dest: "MATU",
    dist: "84",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "137",
    rtid: "2068",
    dep: "SKNG",
    dest: "WBGG",
    dist: "130",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "138",
    rtid: "2069",
    dep: "WBGG",
    dest: "SKNG",
    dist: "130",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "139",
    rtid: "2070",
    dep: "PLOH",
    dest: "WBGG",
    dist: "95",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "140",
    rtid: "2071",
    dep: "WBGG",
    dest: "PLOH",
    dist: "95",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "141",
    rtid: "2072",
    dep: "SMBN",
    dest: "WBGG",
    dist: "17",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "142",
    rtid: "2073",
    dep: "WBGG",
    dest: "SMBN",
    dist: "17",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "143",
    rtid: "2074",
    dep: "PUSA",
    dest: "WBGG",
    dist: "70",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "144",
    rtid: "2075",
    dep: "WBGG",
    dest: "PUSA",
    dist: "70",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "145",
    rtid: "2076",
    dep: "KGSA",
    dest: "WBGG",
    dist: "84",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "146",
    rtid: "2077",
    dep: "WBGG",
    dest: "KGSA",
    dist: "84",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "147",
    rtid: "2078",
    dep: "RJNG",
    dest: "WBGG",
    dist: "55",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "148",
    rtid: "2079",
    dep: "WBGG",
    dest: "RJNG",
    dist: "55",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "149",
    rtid: "2080",
    dep: "SAKE",
    dest: "WBGG",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "150",
    rtid: "2081",
    dep: "WBGG",
    dest: "SAKE",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "151",
    rtid: "2082",
    dep: "WBKD",
    dest: "WBGG",
    dist: "586",
    routedesc: "G580",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "152",
    rtid: "2083",
    dep: "RJAA",
    dest: "WBGG",
    dist: "567",
    routedesc: "B348 G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 5 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "153",
    rtid: "2084",
    dep: "RKSA",
    dest: "WBGG",
    dist: "567",
    routedesc: "B348 G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "154",
    rtid: "2085",
    dep: "RPLL",
    dest: "WBGG",
    dist: "567",
    routedesc: "B348 G580",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "155",
    rtid: "2086",
    dep: "WBGG",
    dest: "VGZR",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "156",
    rtid: "2087",
    dep: "VGZR",
    dest: "WBGG",
    dist: "113",
    routedesc: "M761",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "157",
    rtid: "2088",
    dep: "SMBR",
    dest: "WBGG",
    dist: "8",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "158",
    rtid: "2089",
    dep: "KRGS",
    dest: "WBGG",
    dist: "55",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "159",
    rtid: "2090",
    dep: "KABA",
    dest: "WBGG",
    dist: "119",
    routedesc: "DOM",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "160",
    rtid: "2091",
    dep: "LMNK",
    dest: "WBGG",
    dist: "85",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "161",
    rtid: "2092",
    dep: "WBGG",
    dest: "EKRI",
    dist: "55",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "162",
    rtid: "2093",
    dep: "WBGG",
    dest: "BNAT",
    dist: "27",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "163",
    rtid: "2094",
    dep: "WBGG",
    dest: "TTAU",
    dist: "194",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "164",
    rtid: "2094",
    dep: "WBGG",
    dest: "SMJN",
    dist: "27",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "165",
    rtid: "2095",
    dep: "NYBR",
    dest: "WBGG",
    dist: "75",
    routedesc: "LAN4",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "166",
    rtid: "2096",
    dep: "WBGG",
    dest: "PPPS",
    dist: "30",
    routedesc: "ALN",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "167",
    rtid: "2097",
    dep: "LWIH",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "168",
    rtid: "2098",
    dep: "SLGU",
    dest: "WBGG",
    dist: "111",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "169",
    rtid: "2099",
    dep: "WBGG",
    dest: "SBAU",
    dist: "32",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "170",
    rtid: "2100",
    dep: "WBGG",
    dest: "SMLJ",
    dist: "194",
    routedesc: "DCA 194",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "171",
    rtid: "2101",
    dep: "SDOK",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "172",
    rtid: "2101",
    dep: "WBGG",
    dest: "LOCL",
    dist: "194",
    routedesc: "DCT 194 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "173",
    rtid: "2102",
    dep: "WBGG",
    dest: "TMEL",
    dist: "50",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "174",
    rtid: "2103",
    dep: "WBGG",
    dest: "KPYG",
    dist: "40",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "175",
    rtid: "2104",
    dep: "WBGG",
    dest: "TGLM",
    dist: "30",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "176",
    rtid: "2105",
    dep: "PPAT",
    dest: "WBGG",
    dist: "75",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "177",
    rtid: "2106",
    dep: "WBGG",
    dest: "VDSR",
    dist: "457",
    routedesc: "G580 BRU M768 ASISU",
    cs: "ALN",
    cat: "I"
  },
  {
    ln: "178",
    rtid: "2107",
    dep: "WBGG",
    dest: "KSAI",
    dist: "95",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "179",
    rtid: "2108",
    dep: "WBGG",
    dest: "WBGP",
    dist: "165",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "180",
    rtid: "2109",
    dep: "TLAI",
    dest: "WBGG",
    dist: "20",
    routedesc: "DCT",
    cs: "SC4",
    cat: "D"
  },
  {
    ln: "181",
    rtid: "2110",
    dep: "PLIE",
    dest: "WBGG",
    dist: "30",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "182",
    rtid: "2111",
    dep: "WBGG",
    dest: "WBGR",
    dist: "281",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "183",
    rtid: "2112",
    dep: "NGBH",
    dest: "WBGG",
    dist: "112",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "184",
    rtid: "2113",
    dep: "SRYK",
    dest: "WBGG",
    dist: "30",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "185",
    rtid: "2114",
    dep: "WBGG",
    dest: "YBRM",
    dist: "19",
    routedesc: "PAPSA R455",
    cs: "ALS",
    cat: "D"
  },
  {
    ln: "186",
    rtid: "2115",
    dep: "WBGG",
    dest: "MRDG",
    dist: "90",
    routedesc: "ALN",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "187",
    rtid: "2116",
    dep: "WBGG",
    dest: "MJAU",
    dist: "119",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "188",
    rtid: "2117",
    dep: "WBGG",
    dest: "LOCL",
    dist: "10",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "189",
    rtid: "2118",
    dep: "WBGG",
    dest: "LOCL",
    dist: "492",
    routedesc: "DCT 492 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "190",
    rtid: "2119",
    dep: "WBGG",
    dest: "LOCL",
    dist: "458",
    routedesc: "DCT 458 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 6 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "191",
    rtid: "2120",
    dep: "WBGG",
    dest: "LOCL",
    dist: "302",
    routedesc: "DCT 302 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "192",
    rtid: "2121",
    dep: "WBGG",
    dest: "LOCL",
    dist: "470",
    routedesc: "DCT 470 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "193",
    rtid: "2122",
    dep: "WBGG",
    dest: "LOCL",
    dist: "536",
    routedesc: "DCT 536 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "194",
    rtid: "2123",
    dep: "WBGG",
    dest: "LOCL",
    dist: "284",
    routedesc: "DCT 284 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "195",
    rtid: "2124",
    dep: "WBGG",
    dest: "LOCL",
    dist: "300",
    routedesc: "DCT 300 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "196",
    rtid: "2125",
    dep: "WBGG",
    dest: "SAMU",
    dist: "35",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "197",
    rtid: "2125",
    dep: "WBGG",
    dest: "RPVP",
    dist: "567",
    routedesc: "G580 B348",
    cs: "SC2",
    cat: "D"
  },
  {
    ln: "198",
    rtid: "2126",
    dep: "SPOH",
    dest: "WBGG",
    dist: "80",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "199",
    rtid: "2127",
    dep: "WBGG",
    dest: "SERN",
    dist: "24",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "200",
    rtid: "2128",
    dep: "WBGG",
    dest: "BOHG",
    dist: "3",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "201",
    rtid: "2129",
    dep: "WBGG",
    dest: "LOCL",
    dist: "106",
    routedesc: "DCT 106 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "202",
    rtid: "2130",
    dep: "WBGG",
    dest: "LOCL",
    dist: "250",
    routedesc: "DCT 250 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "203",
    rtid: "2131",
    dep: "WBGG",
    dest: "LOCL",
    dist: "132",
    routedesc: "DCT 132 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "204",
    rtid: "2132",
    dep: "WBGG",
    dest: "LOCL",
    dist: "190",
    routedesc: "DCT 190 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "205",
    rtid: "2133",
    dep: "WBGG",
    dest: "LOCL",
    dist: "136",
    routedesc: "DCT 136 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "206",
    rtid: "2134",
    dep: "WBGG",
    dest: "LOCL",
    dist: "192",
    routedesc: "DCT 192 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "207",
    rtid: "2135",
    dep: "WBGG",
    dest: "LOCT",
    dist: "180",
    routedesc: "DCT 180 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "208",
    rtid: "2136",
    dep: "WBGG",
    dest: "LOCL",
    dist: "146",
    routedesc: "DCT 146 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "209",
    rtid: "2137",
    dep: "WBGG",
    dest: "LOCL",
    dist: "158",
    routedesc: "DCT 158 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "210",
    rtid: "2138",
    dep: "WBGG",
    dest: "LOCL",
    dist: "200",
    routedesc: "DCT 200 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "211",
    rtid: "2139",
    dep: "WBGG",
    dest: "LOCL",
    dist: "166",
    routedesc: "DCT 166 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "212",
    rtid: "2140",
    dep: "WBGG",
    dest: "SMHN",
    dist: "48",
    routedesc: "DCT 48 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "213",
    rtid: "2141",
    dep: "WBGG",
    dest: "LOCL",
    dist: "142",
    routedesc: "DCT 142 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "214",
    rtid: "2142",
    dep: "WBGG",
    dest: "SMHN",
    dist: "154",
    routedesc: "DCT 154 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "215",
    rtid: "2143",
    dep: "WBGG",
    dest: "SMHN",
    dist: "128",
    routedesc: "DCT 128 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "216",
    rtid: "2144",
    dep: "WBGG",
    dest: "LOCL",
    dist: "160",
    routedesc: "DCT 160 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "217",
    rtid: "2145",
    dep: "WBGG",
    dest: "JLAU",
    dist: "103",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "218",
    rtid: "2146",
    dep: "WBGG",
    dest: "TBTH",
    dist: "25",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "219",
    rtid: "2147",
    dep: "WBGG",
    dest: "MDNG",
    dist: "28",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "220",
    rtid: "2148",
    dep: "WBGG",
    dest: "HSKC",
    dist: "5",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "221",
    rtid: "2149",
    dep: "WBGG",
    dest: "DBAK",
    dist: "69",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "222",
    rtid: "2150",
    dep: "WBGG",
    dest: "SONG",
    dist: "140",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "223",
    rtid: "2151",
    dep: "WBGG",
    dest: "LNDU",
    dist: "602",
    routedesc: "DCT 602 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "224",
    rtid: "2152",
    dep: "WBGG",
    dest: "SMBN",
    dist: "18",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "225",
    rtid: "2153",
    dep: "WBGG",
    dest: "LOCL",
    dist: "178",
    routedesc: "DCT 178 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "226",
    rtid: "2154",
    dep: "WBGG",
    dest: "LNDU",
    dist: "362",
    routedesc: "DCT 362 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "227",
    rtid: "2155",
    dep: "WBGG",
    dest: "SGNW",
    dist: "35",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "228",
    rtid: "2156",
    dep: "WBGG",
    dest: "SRBG",
    dist: "40",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 7 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "229",
    rtid: "2157",
    dep: "SKUA",
    dest: "WBGG",
    dist: "122",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "230",
    rtid: "2158",
    dep: "WBGG",
    dest: "LOCL",
    dist: "264",
    routedesc: "DCT 264 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "231",
    rtid: "2159",
    dep: "WBGG",
    dest: "BAKO",
    dist: "12",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "232",
    rtid: "2160",
    dep: "KBNG",
    dest: "WBGG",
    dist: "53",
    routedesc: "DCT",
    cs: "ALN",
    cat: "D"
  },
  {
    ln: "233",
    rtid: "2161",
    dep: "WBGG",
    dest: "LOCL",
    dist: "256",
    routedesc: "DCT 256 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "234",
    rtid: "2162",
    dep: "WBGG",
    dest: "LOCL",
    dist: "466",
    routedesc: "DCT 466 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "235",
    rtid: "2163",
    dep: "WBGG",
    dest: "LOCL",
    dist: "266",
    routedesc: "DCT 266 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "236",
    rtid: "2164",
    dep: "WBGG",
    dest: "LNGA",
    dist: "52",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "237",
    rtid: "2165",
    dep: "WBGG",
    dest: "LOCL",
    dist: "196",
    routedesc: "DCT 196 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "238",
    rtid: "2166",
    dep: "WBGG",
    dest: "ZGSZ",
    dist: "545",
    routedesc: "G580 M754",
    cs: "SC2",
    cat: "I"
  },
  {
    ln: "239",
    rtid: "2167",
    dep: "WBGG",
    dest: "DALT",
    dist: "126",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "240",
    rtid: "2168",
    dep: "WBGG",
    dest: "LOCL",
    dist: "74",
    routedesc: "DCT 74 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "241",
    rtid: "2169",
    dep: "WBGG",
    dest: "LOCL",
    dist: "164",
    routedesc: "DCT 164 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "242",
    rtid: "2170",
    dep: "WBGG",
    dest: "BTAI",
    dist: "91",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "243",
    rtid: "2171",
    dep: "WBGG",
    dest: "MLDM",
    dist: "45",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "244",
    rtid: "2172",
    dep: "WBGG",
    dest: "PLDG",
    dist: "112",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "245",
    rtid: "2173",
    dep: "WBGG",
    dest: "MRTS",
    dist: "15",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "246",
    rtid: "2174",
    dep: "WBGG",
    dest: "KNWT",
    dist: "118",
    routedesc: "DCT",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "247",
    rtid: "2175",
    dep: "WBGG",
    dest: "LOCL",
    dist: "352",
    routedesc: "DCT 352 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "248",
    rtid: "2176",
    dep: "WBGG",
    dest: "LOCL",
    dist: "298",
    routedesc: "DCT 298 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "249",
    rtid: "2177",
    dep: "WBGG",
    dest: "LOCL",
    dist: "356",
    routedesc: "DCT 356 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "250",
    rtid: "2178",
    dep: "WBGG",
    dest: "LOCL",
    dist: "552",
    routedesc: "DCT 552 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "251",
    rtid: "2179",
    dep: "WBGG",
    dest: "LOCL",
    dist: "278",
    routedesc: "DCT 278 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "252",
    rtid: "2180",
    dep: "WBGG",
    dest: "LOCL",
    dist: "370",
    routedesc: "DCT 370 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "253",
    rtid: "2181",
    dep: "WBGG",
    dest: "LOCL",
    dist: "432",
    routedesc: "DCT 432 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "254",
    rtid: "2182",
    dep: "WBGG",
    dest: "LOCL",
    dist: "414",
    routedesc: "DCT 414 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "255",
    rtid: "2183",
    dep: "WBGG",
    dest: "LOCL",
    dist: "228",
    routedesc: "DCT 228 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "256",
    rtid: "2184",
    dep: "WBGG",
    dest: "LOCL",
    dist: "330",
    routedesc: "DCT 330 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "257",
    rtid: "2185",
    dep: "WBGG",
    dest: "LOCL",
    dist: "24",
    routedesc: "DCT 24 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "258",
    rtid: "2186",
    dep: "WBGG",
    dest: "LOCL",
    dist: "320",
    routedesc: "DCT 320 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "259",
    rtid: "2187",
    dep: "WBGG",
    dest: "LOCL",
    dist: "598",
    routedesc: "DCT 598 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "260",
    rtid: "2188",
    dep: "WBGG",
    dest: "LOCL",
    dist: "238",
    routedesc: "DCT 238 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "261",
    rtid: "2189",
    dep: "WBGG",
    dest: "LOCL",
    dist: "124",
    routedesc: "DCT 124 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "262",
    rtid: "2190",
    dep: "WBGG",
    dest: "LOCL",
    dist: "234",
    routedesc: "DCT 234 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "263",
    rtid: "2191",
    dep: "WBGG",
    dest: "LOCL",
    dist: "110",
    routedesc: "DCT 110 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "264",
    rtid: "2192",
    dep: "WBGG",
    dest: "LOCL",
    dist: "122",
    routedesc: "DCT 122 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "265",
    rtid: "2193",
    dep: "WBGG",
    dest: "LOCL",
    dist: "212",
    routedesc: "DCT 212 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "266",
    rtid: "2194",
    dep: "WBGG",
    dest: "LOCL",
    dist: "188",
    routedesc: "DCT 188 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "",
    field2: "Civil Aviation Authority Of Malaysia (CAAM)",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "List of Routes - ALL",
    field17: "",
    field18: "",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "",
    field2: "Air Navigation Facilities Charges System",
    field3: "",
    field4: "",
    rtid: "",
    dep: "",
    dest: "",
    dist: "",
    routedesc: "",
    field15: "",
    field16: "",
    field17: "",
    field18: "3/3/2020  2:16:06PM  Page 8 of 8",
    field19: "",
    field20: "",
    cs: "",
    cat: ""
  },
  {
    ln: "LN",
    rtid: "RTID",
    dep: "DEP",
    dest: "DEST",
    field11: "DIST",
    dist: "",
    routedesc: "Route Description",
    cs: "CS",
    cat: "Cat"
  },
  {
    ln: "267",
    rtid: "2195",
    dep: "WBGG",
    dest: "LOCL",
    dist: "244",
    routedesc: "DCT 244 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "268",
    rtid: "2196",
    dep: "WBGG",
    dest: "LOCL",
    dist: "82",
    routedesc: "DCT 82 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "269",
    rtid: "2197",
    dep: "WBGG",
    dest: "LOCL",
    dist: "94",
    routedesc: "DCT 94 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "270",
    rtid: "2198",
    dep: "WBGG",
    dest: "LOCL",
    dist: "120",
    routedesc: "DCT 120 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "271",
    rtid: "2199",
    dep: "WBGG",
    dest: "LOCL",
    dist: "130",
    routedesc: "DCT 130 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "272",
    rtid: "2200",
    dep: "WBGG",
    dest: "LOCL",
    dist: "118",
    routedesc: "DCT 118 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "273",
    rtid: "2201",
    dep: "WBGG",
    dest: "LOCL",
    dist: "116",
    routedesc: "DCT 116 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "274",
    rtid: "2202",
    dep: "WBGG",
    dest: "LOCL",
    dist: "126",
    routedesc: "DCT 126 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "275",
    rtid: "2203",
    dep: "WBGG",
    dest: "LOCL",
    dist: "46",
    routedesc: "DCT 46 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "276",
    rtid: "2204",
    dep: "WBGG",
    dest: "LOCL",
    dist: "206",
    routedesc: "DCT 206 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "277",
    rtid: "2205",
    dep: "WBGG",
    dest: "LOCL",
    dist: "44",
    routedesc: "DCT 44 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "278",
    rtid: "2206",
    dep: "WBGG",
    dest: "LOCL",
    dist: "84",
    routedesc: "DCT 84 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "279",
    rtid: "2207",
    dep: "WBGG",
    dest: "LOCL",
    dist: "426",
    routedesc: "DCT 426 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "280",
    rtid: "2208",
    dep: "WBGG",
    dest: "LOCL",
    dist: "524",
    routedesc: "DCT 524 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "281",
    rtid: "2209",
    dep: "WBGG",
    dest: "LOCL",
    dist: "660",
    routedesc: "DCT 660 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "282",
    rtid: "2210",
    dep: "WBGG",
    dest: "LOCL",
    dist: "402",
    routedesc: "DCT 402 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "283",
    rtid: "2211",
    dep: "WBGG",
    dest: "LOCL",
    dist: "114",
    routedesc: "DCT 114 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "284",
    rtid: "2212",
    dep: "WBGG",
    dest: "LOCL",
    dist: "186",
    routedesc: "DCT 186 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "285",
    rtid: "2213",
    dep: "WBGG",
    dest: "LOCL",
    dist: "89",
    routedesc: "DCT 89 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "286",
    rtid: "2214",
    dep: "WBGG",
    dest: "LOCL",
    dist: "148",
    routedesc: "DCT 148 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "287",
    rtid: "2215",
    dep: "WBGG",
    dest: "LOCL",
    dist: "201",
    routedesc: "DCT 201 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "288",
    rtid: "2216",
    dep: "WBGG",
    dest: "LOCL",
    dist: "296",
    routedesc: "DCT 296 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "289",
    rtid: "2217",
    dep: "WBGG",
    dest: "LOCL",
    dist: "280",
    routedesc: "DCT 280 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "290",
    rtid: "2218",
    dep: "WBGG",
    dest: "LOCL",
    dist: "224",
    routedesc: "DCT 224 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "291",
    rtid: "2219",
    dep: "WBGG",
    dest: "LOCL",
    dist: "260",
    routedesc: "DCT 260 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "292",
    rtid: "2220",
    dep: "WBGG",
    dest: "LOCL",
    dist: "430",
    routedesc: "DCT 430 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "293",
    rtid: "2221",
    dep: "WBGG",
    dest: "LOCL",
    dist: "308",
    routedesc: "DCT 308 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "294",
    rtid: "2222",
    dep: "WBGG",
    dest: "LOCL",
    dist: "258",
    routedesc: "DCT 258 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "295",
    rtid: "2223",
    dep: "WBGG",
    dest: "LOCL",
    dist: "182",
    routedesc: "DCT 182 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "296",
    rtid: "2224",
    dep: "WBGG",
    dest: "LOCL",
    dist: "104",
    routedesc: "DCT 104 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "297",
    rtid: "2225",
    dep: "WBGG",
    dest: "LOCL",
    dist: "144",
    routedesc: "DCT 144 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "298",
    rtid: "2226",
    dep: "WBGG",
    dest: "LOCL",
    dist: "108",
    routedesc: "DCT 108 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  },
  {
    ln: "299",
    rtid: "2227",
    dep: "WBGG",
    dest: "LOCL",
    dist: "168",
    routedesc: "DCT 168 AERIAL SURVEY",
    cs: "SC1",
    cat: "D"
  }
];
